services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    environment:
      - CLICKHOUSE_DB=datamart_layer
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    restart: no
    ports:
      - "8123:8123"
      - "9000:9000" 
      - "9005:9005"